version = 0.1

[default]
region = "us-east-1"
parallel = true
lint = true

[default.deploy.parameters]
s3_prefix = "cmi-backend-lambdas-parca-application"
disable_rollback = false
resolve_s3 = true
capabilities = "CAPABILITY_IAM"

[sandbox.deploy.parameters]
stack_name = "sandbox-cmi-backend-lambdas-parca-application"
confirm_changeset = false
parameter_overrides = "stage=\"sandbox\""
resolve_s3 = true
capabilities = "CAPABILITY_IAM"

[dev.deploy.parameters]
stack_name = "dev-cmi-backend-lambdas-parca-application"
confirm_changeset = false
parameter_overrides = "stage=\"dev\""
resolve_s3 = true
capabilities = "CAPABILITY_IAM"

[qa.deploy.parameters]
stack_name = "qa-cmi-backend-lambdas-parca-application"
confirm_changeset = false
parameter_overrides = "stage=\"qa\""
resolve_s3 = true
capabilities = "CAPABILITY_IAM"

[uat.deploy.parameters]
stack_name = "uat-cmi-backend-lambdas-parca-application"
confirm_changeset = true
parameter_overrides = "stage=\"uat\""
resolve_s3 = true
capabilities = "CAPABILITY_IAM"

[prod.deploy.parameters]
stack_name = "prod-cmi-backend-lambdas-parca-application"
confirm_changeset = false
parameter_overrides = "stage=\"prod\""
resolve_s3 = true
capabilities = "CAPABILITY_IAM"
